/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.UUID;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class FreePassInput {
  
  @SerializedName("articleId")
  private UUID articleId = null;
  @SerializedName("expiryTime")
  private String expiryTime = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getArticleId() {
    return articleId;
  }
  public void setArticleId(UUID articleId) {
    this.articleId = articleId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getExpiryTime() {
    return expiryTime;
  }
  public void setExpiryTime(String expiryTime) {
    this.expiryTime = expiryTime;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FreePassInput freePassInput = (FreePassInput) o;
    return (this.articleId == null ? freePassInput.articleId == null : this.articleId.equals(freePassInput.articleId)) &&
        (this.expiryTime == null ? freePassInput.expiryTime == null : this.expiryTime.equals(freePassInput.expiryTime));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.articleId == null ? 0: this.articleId.hashCode());
    result = 31 * result + (this.expiryTime == null ? 0: this.expiryTime.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class FreePassInput {\n");
    
    sb.append("  articleId: ").append(articleId).append("\n");
    sb.append("  expiryTime: ").append(expiryTime).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
