/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GdprConsent {
  
  @SerializedName("brand")
  private String brand = null;
  @SerializedName("consentKey")
  private String consentKey = null;
  @SerializedName("value")
  private Boolean value = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getBrand() {
    return brand;
  }
  public void setBrand(String brand) {
    this.brand = brand;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getConsentKey() {
    return consentKey;
  }
  public void setConsentKey(String consentKey) {
    this.consentKey = consentKey;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getValue() {
    return value;
  }
  public void setValue(Boolean value) {
    this.value = value;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GdprConsent gdprConsent = (GdprConsent) o;
    return (this.brand == null ? gdprConsent.brand == null : this.brand.equals(gdprConsent.brand)) &&
        (this.consentKey == null ? gdprConsent.consentKey == null : this.consentKey.equals(gdprConsent.consentKey)) &&
        (this.value == null ? gdprConsent.value == null : this.value.equals(gdprConsent.value));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.brand == null ? 0: this.brand.hashCode());
    result = 31 * result + (this.consentKey == null ? 0: this.consentKey.hashCode());
    result = 31 * result + (this.value == null ? 0: this.value.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GdprConsent {\n");
    
    sb.append("  brand: ").append(brand).append("\n");
    sb.append("  consentKey: ").append(consentKey).append("\n");
    sb.append("  value: ").append(value).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
