/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class GdprConsent {
  
  @SerializedName("key")
  private String key = null;
  @SerializedName("val")
  private Boolean val = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getKey() {
    return key;
  }
  public void setKey(String key) {
    this.key = key;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getVal() {
    return val;
  }
  public void setVal(Boolean val) {
    this.val = val;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GdprConsent gdprConsent = (GdprConsent) o;
    return (this.key == null ? gdprConsent.key == null : this.key.equals(gdprConsent.key)) &&
        (this.val == null ? gdprConsent.val == null : this.val.equals(gdprConsent.val));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.key == null ? 0: this.key.hashCode());
    result = 31 * result + (this.val == null ? 0: this.val.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GdprConsent {\n");
    
    sb.append("  key: ").append(key).append("\n");
    sb.append("  val: ").append(val).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
