/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.InlineResponse415UnsupportedMediaType;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse415 {
  
  @SerializedName("http_code")
  private Integer httpCode = null;
  @SerializedName("unsupported_media_type")
  private InlineResponse415UnsupportedMediaType unsupportedMediaType = null;
  public enum HttpStatusEnum {
     Unsupported media type, 
  };
  @SerializedName("http_status")
  private HttpStatusEnum httpStatus = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getHttpCode() {
    return httpCode;
  }
  public void setHttpCode(Integer httpCode) {
    this.httpCode = httpCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public InlineResponse415UnsupportedMediaType getUnsupportedMediaType() {
    return unsupportedMediaType;
  }
  public void setUnsupportedMediaType(InlineResponse415UnsupportedMediaType unsupportedMediaType) {
    this.unsupportedMediaType = unsupportedMediaType;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public HttpStatusEnum getHttpStatus() {
    return httpStatus;
  }
  public void setHttpStatus(HttpStatusEnum httpStatus) {
    this.httpStatus = httpStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse415 inlineResponse415 = (InlineResponse415) o;
    return (this.httpCode == null ? inlineResponse415.httpCode == null : this.httpCode.equals(inlineResponse415.httpCode)) &&
        (this.unsupportedMediaType == null ? inlineResponse415.unsupportedMediaType == null : this.unsupportedMediaType.equals(inlineResponse415.unsupportedMediaType)) &&
        (this.httpStatus == null ? inlineResponse415.httpStatus == null : this.httpStatus.equals(inlineResponse415.httpStatus));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.httpCode == null ? 0: this.httpCode.hashCode());
    result = 31 * result + (this.unsupportedMediaType == null ? 0: this.unsupportedMediaType.hashCode());
    result = 31 * result + (this.httpStatus == null ? 0: this.httpStatus.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse415 {\n");
    
    sb.append("  httpCode: ").append(httpCode).append("\n");
    sb.append("  unsupportedMediaType: ").append(unsupportedMediaType).append("\n");
    sb.append("  httpStatus: ").append(httpStatus).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
