/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse4032EmailAddressInUse {
  
  @SerializedName("merge_token")
  private String mergeToken = null;
  public enum DescriptionEnum {
     User has another record registered. Please merge the accounts., 
  };
  @SerializedName("description")
  private DescriptionEnum description = null;
  @SerializedName("existing_provider")
  private String existingProvider = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMergeToken() {
    return mergeToken;
  }
  public void setMergeToken(String mergeToken) {
    this.mergeToken = mergeToken;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public DescriptionEnum getDescription() {
    return description;
  }
  public void setDescription(DescriptionEnum description) {
    this.description = description;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getExistingProvider() {
    return existingProvider;
  }
  public void setExistingProvider(String existingProvider) {
    this.existingProvider = existingProvider;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse4032EmailAddressInUse inlineResponse4032EmailAddressInUse = (InlineResponse4032EmailAddressInUse) o;
    return (this.mergeToken == null ? inlineResponse4032EmailAddressInUse.mergeToken == null : this.mergeToken.equals(inlineResponse4032EmailAddressInUse.mergeToken)) &&
        (this.description == null ? inlineResponse4032EmailAddressInUse.description == null : this.description.equals(inlineResponse4032EmailAddressInUse.description)) &&
        (this.existingProvider == null ? inlineResponse4032EmailAddressInUse.existingProvider == null : this.existingProvider.equals(inlineResponse4032EmailAddressInUse.existingProvider));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.mergeToken == null ? 0: this.mergeToken.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.existingProvider == null ? 0: this.existingProvider.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse4032EmailAddressInUse {\n");
    
    sb.append("  mergeToken: ").append(mergeToken).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  existingProvider: ").append(existingProvider).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
