/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.InlineResponse403InvalidCredentials;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse403 {
  
  @SerializedName("http_code")
  private Integer httpCode = null;
  public enum HttpStatusEnum {
     Forbidden, 
  };
  @SerializedName("http_status")
  private HttpStatusEnum httpStatus = null;
  @SerializedName("invalid_credentials")
  private InlineResponse403InvalidCredentials invalidCredentials = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getHttpCode() {
    return httpCode;
  }
  public void setHttpCode(Integer httpCode) {
    this.httpCode = httpCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public HttpStatusEnum getHttpStatus() {
    return httpStatus;
  }
  public void setHttpStatus(HttpStatusEnum httpStatus) {
    this.httpStatus = httpStatus;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public InlineResponse403InvalidCredentials getInvalidCredentials() {
    return invalidCredentials;
  }
  public void setInvalidCredentials(InlineResponse403InvalidCredentials invalidCredentials) {
    this.invalidCredentials = invalidCredentials;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse403 inlineResponse403 = (InlineResponse403) o;
    return (this.httpCode == null ? inlineResponse403.httpCode == null : this.httpCode.equals(inlineResponse403.httpCode)) &&
        (this.httpStatus == null ? inlineResponse403.httpStatus == null : this.httpStatus.equals(inlineResponse403.httpStatus)) &&
        (this.invalidCredentials == null ? inlineResponse403.invalidCredentials == null : this.invalidCredentials.equals(inlineResponse403.invalidCredentials));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.httpCode == null ? 0: this.httpCode.hashCode());
    result = 31 * result + (this.httpStatus == null ? 0: this.httpStatus.hashCode());
    result = 31 * result + (this.invalidCredentials == null ? 0: this.invalidCredentials.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse403 {\n");
    
    sb.append("  httpCode: ").append(httpCode).append("\n");
    sb.append("  httpStatus: ").append(httpStatus).append("\n");
    sb.append("  invalidCredentials: ").append(invalidCredentials).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
