/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import org.openapitools.client.model.InlineResponse4031AccessTokenExpired;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class InlineResponse4031 {
  
  @SerializedName("http_code")
  private Integer httpCode = null;
  @SerializedName("access_token_expired")
  private InlineResponse4031AccessTokenExpired accessTokenExpired = null;
  public enum HttpStatusEnum {
     Forbidden, 
  };
  @SerializedName("http_status")
  private HttpStatusEnum httpStatus = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public Integer getHttpCode() {
    return httpCode;
  }
  public void setHttpCode(Integer httpCode) {
    this.httpCode = httpCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public InlineResponse4031AccessTokenExpired getAccessTokenExpired() {
    return accessTokenExpired;
  }
  public void setAccessTokenExpired(InlineResponse4031AccessTokenExpired accessTokenExpired) {
    this.accessTokenExpired = accessTokenExpired;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public HttpStatusEnum getHttpStatus() {
    return httpStatus;
  }
  public void setHttpStatus(HttpStatusEnum httpStatus) {
    this.httpStatus = httpStatus;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse4031 inlineResponse4031 = (InlineResponse4031) o;
    return (this.httpCode == null ? inlineResponse4031.httpCode == null : this.httpCode.equals(inlineResponse4031.httpCode)) &&
        (this.accessTokenExpired == null ? inlineResponse4031.accessTokenExpired == null : this.accessTokenExpired.equals(inlineResponse4031.accessTokenExpired)) &&
        (this.httpStatus == null ? inlineResponse4031.httpStatus == null : this.httpStatus.equals(inlineResponse4031.httpStatus));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.httpCode == null ? 0: this.httpCode.hashCode());
    result = 31 * result + (this.accessTokenExpired == null ? 0: this.accessTokenExpired.hashCode());
    result = 31 * result + (this.httpStatus == null ? 0: this.httpStatus.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse4031 {\n");
    
    sb.append("  httpCode: ").append(httpCode).append("\n");
    sb.append("  accessTokenExpired: ").append(accessTokenExpired).append("\n");
    sb.append("  httpStatus: ").append(httpStatus).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
