/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.UUID;
import org.openapitools.client.model.GdprConsent;
import org.openapitools.client.model.LegalConsent;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class JanrainUser {
  
  @SerializedName("uuid")
  private UUID uuid = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("firstName")
  private String firstName = null;
  @SerializedName("lastName")
  private String lastName = null;
  @SerializedName("middleName")
  private String middleName = null;
  @SerializedName("consent")
  private List<GdprConsent> consent = null;
  @SerializedName("legal")
  private List<LegalConsent> legal = null;
  @SerializedName("cusno")
  private String cusno = null;
  @SerializedName("otherCusnos")
  private List<String> otherCusnos = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getUuid() {
    return uuid;
  }
  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMiddleName() {
    return middleName;
  }
  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<GdprConsent> getConsent() {
    return consent;
  }
  public void setConsent(List<GdprConsent> consent) {
    this.consent = consent;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<LegalConsent> getLegal() {
    return legal;
  }
  public void setLegal(List<LegalConsent> legal) {
    this.legal = legal;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCusno() {
    return cusno;
  }
  public void setCusno(String cusno) {
    this.cusno = cusno;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<String> getOtherCusnos() {
    return otherCusnos;
  }
  public void setOtherCusnos(List<String> otherCusnos) {
    this.otherCusnos = otherCusnos;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JanrainUser janrainUser = (JanrainUser) o;
    return (this.uuid == null ? janrainUser.uuid == null : this.uuid.equals(janrainUser.uuid)) &&
        (this.email == null ? janrainUser.email == null : this.email.equals(janrainUser.email)) &&
        (this.firstName == null ? janrainUser.firstName == null : this.firstName.equals(janrainUser.firstName)) &&
        (this.lastName == null ? janrainUser.lastName == null : this.lastName.equals(janrainUser.lastName)) &&
        (this.middleName == null ? janrainUser.middleName == null : this.middleName.equals(janrainUser.middleName)) &&
        (this.consent == null ? janrainUser.consent == null : this.consent.equals(janrainUser.consent)) &&
        (this.legal == null ? janrainUser.legal == null : this.legal.equals(janrainUser.legal)) &&
        (this.cusno == null ? janrainUser.cusno == null : this.cusno.equals(janrainUser.cusno)) &&
        (this.otherCusnos == null ? janrainUser.otherCusnos == null : this.otherCusnos.equals(janrainUser.otherCusnos));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.uuid == null ? 0: this.uuid.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.middleName == null ? 0: this.middleName.hashCode());
    result = 31 * result + (this.consent == null ? 0: this.consent.hashCode());
    result = 31 * result + (this.legal == null ? 0: this.legal.hashCode());
    result = 31 * result + (this.cusno == null ? 0: this.cusno.hashCode());
    result = 31 * result + (this.otherCusnos == null ? 0: this.otherCusnos.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class JanrainUser {\n");
    
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  middleName: ").append(middleName).append("\n");
    sb.append("  consent: ").append(consent).append("\n");
    sb.append("  legal: ").append(legal).append("\n");
    sb.append("  cusno: ").append(cusno).append("\n");
    sb.append("  otherCusnos: ").append(otherCusnos).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
