/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LegalConsent {
  
  @SerializedName("screenName")
  private String screenName = null;
  @SerializedName("consentId")
  private String consentId = null;
  @SerializedName("dateAccepted")
  private String dateAccepted = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getScreenName() {
    return screenName;
  }
  public void setScreenName(String screenName) {
    this.screenName = screenName;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getConsentId() {
    return consentId;
  }
  public void setConsentId(String consentId) {
    this.consentId = consentId;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDateAccepted() {
    return dateAccepted;
  }
  public void setDateAccepted(String dateAccepted) {
    this.dateAccepted = dateAccepted;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LegalConsent legalConsent = (LegalConsent) o;
    return (this.screenName == null ? legalConsent.screenName == null : this.screenName.equals(legalConsent.screenName)) &&
        (this.consentId == null ? legalConsent.consentId == null : this.consentId.equals(legalConsent.consentId)) &&
        (this.dateAccepted == null ? legalConsent.dateAccepted == null : this.dateAccepted.equals(legalConsent.dateAccepted));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.screenName == null ? 0: this.screenName.hashCode());
    result = 31 * result + (this.consentId == null ? 0: this.consentId.hashCode());
    result = 31 * result + (this.dateAccepted == null ? 0: this.dateAccepted.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LegalConsent {\n");
    
    sb.append("  screenName: ").append(screenName).append("\n");
    sb.append("  consentId: ").append(consentId).append("\n");
    sb.append("  dateAccepted: ").append(dateAccepted).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
