/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class LoginDataSoMe {
  
  @SerializedName("provider")
  private String provider = null;
  @SerializedName("someToken")
  private String someToken = null;
  @SerializedName("mergeToken")
  private String mergeToken = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getProvider() {
    return provider;
  }
  public void setProvider(String provider) {
    this.provider = provider;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getSomeToken() {
    return someToken;
  }
  public void setSomeToken(String someToken) {
    this.someToken = someToken;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getMergeToken() {
    return mergeToken;
  }
  public void setMergeToken(String mergeToken) {
    this.mergeToken = mergeToken;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    LoginDataSoMe loginDataSoMe = (LoginDataSoMe) o;
    return (this.provider == null ? loginDataSoMe.provider == null : this.provider.equals(loginDataSoMe.provider)) &&
        (this.someToken == null ? loginDataSoMe.someToken == null : this.someToken.equals(loginDataSoMe.someToken)) &&
        (this.mergeToken == null ? loginDataSoMe.mergeToken == null : this.mergeToken.equals(loginDataSoMe.mergeToken));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.provider == null ? 0: this.provider.hashCode());
    result = 31 * result + (this.someToken == null ? 0: this.someToken.hashCode());
    result = 31 * result + (this.mergeToken == null ? 0: this.mergeToken.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class LoginDataSoMe {\n");
    
    sb.append("  provider: ").append(provider).append("\n");
    sb.append("  someToken: ").append(someToken).append("\n");
    sb.append("  mergeToken: ").append(mergeToken).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
