/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.Date;
import org.openapitools.client.model.PackageCampaign;
import org.openapitools.client.model.PackageOffer;
import org.openapitools.client.model.Paper;
import org.openapitools.client.model.Product;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class ModelPackage {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("info")
  private List<String> info = null;
  @SerializedName("paper")
  private Paper paper = null;
  @SerializedName("digitalOnly")
  private Boolean digitalOnly = null;
  @SerializedName("products")
  private List<Product> products = null;
  @SerializedName("offers")
  private List<PackageOffer> offers = null;
  @SerializedName("campaigns")
  private List<PackageCampaign> campaigns = null;
  @SerializedName("nextDelivery")
  private Date nextDelivery = null;
  @SerializedName("canPause")
  private Boolean canPause = null;
  @SerializedName("canTempAddr")
  private Boolean canTempAddr = null;

  /**
   * Package identifier
   **/
  @ApiModelProperty(required = true, value = "Package identifier")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Package name
   **/
  @ApiModelProperty(required = true, value = "Package name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Package description
   **/
  @ApiModelProperty(required = true, value = "Package description")
  public List<String> getInfo() {
    return info;
  }
  public void setInfo(List<String> info) {
    this.info = info;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Paper getPaper() {
    return paper;
  }
  public void setPaper(Paper paper) {
    this.paper = paper;
  }

  /**
   * All products in this package are digital
   **/
  @ApiModelProperty(required = true, value = "All products in this package are digital")
  public Boolean getDigitalOnly() {
    return digitalOnly;
  }
  public void setDigitalOnly(Boolean digitalOnly) {
    this.digitalOnly = digitalOnly;
  }

  /**
   * The Products contained in a package
   **/
  @ApiModelProperty(required = true, value = "The Products contained in a package")
  public List<Product> getProducts() {
    return products;
  }
  public void setProducts(List<Product> products) {
    this.products = products;
  }

  /**
   * Offers for the package
   **/
  @ApiModelProperty(required = true, value = "Offers for the package")
  public List<PackageOffer> getOffers() {
    return offers;
  }
  public void setOffers(List<PackageOffer> offers) {
    this.offers = offers;
  }

  /**
   * Active campaigns for the package
   **/
  @ApiModelProperty(required = true, value = "Active campaigns for the package")
  public List<PackageCampaign> getCampaigns() {
    return campaigns;
  }
  public void setCampaigns(List<PackageCampaign> campaigns) {
    this.campaigns = campaigns;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getNextDelivery() {
    return nextDelivery;
  }
  public void setNextDelivery(Date nextDelivery) {
    this.nextDelivery = nextDelivery;
  }

  /**
   * Does the package allow delivery pauses
   **/
  @ApiModelProperty(required = true, value = "Does the package allow delivery pauses")
  public Boolean getCanPause() {
    return canPause;
  }
  public void setCanPause(Boolean canPause) {
    this.canPause = canPause;
  }

  /**
   * Does the package allow temporary address changes
   **/
  @ApiModelProperty(required = true, value = "Does the package allow temporary address changes")
  public Boolean getCanTempAddr() {
    return canTempAddr;
  }
  public void setCanTempAddr(Boolean canTempAddr) {
    this.canTempAddr = canTempAddr;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ModelPackage _package = (ModelPackage) o;
    return (this.id == null ? _package.id == null : this.id.equals(_package.id)) &&
        (this.name == null ? _package.name == null : this.name.equals(_package.name)) &&
        (this.info == null ? _package.info == null : this.info.equals(_package.info)) &&
        (this.paper == null ? _package.paper == null : this.paper.equals(_package.paper)) &&
        (this.digitalOnly == null ? _package.digitalOnly == null : this.digitalOnly.equals(_package.digitalOnly)) &&
        (this.products == null ? _package.products == null : this.products.equals(_package.products)) &&
        (this.offers == null ? _package.offers == null : this.offers.equals(_package.offers)) &&
        (this.campaigns == null ? _package.campaigns == null : this.campaigns.equals(_package.campaigns)) &&
        (this.nextDelivery == null ? _package.nextDelivery == null : this.nextDelivery.equals(_package.nextDelivery)) &&
        (this.canPause == null ? _package.canPause == null : this.canPause.equals(_package.canPause)) &&
        (this.canTempAddr == null ? _package.canTempAddr == null : this.canTempAddr.equals(_package.canTempAddr));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.info == null ? 0: this.info.hashCode());
    result = 31 * result + (this.paper == null ? 0: this.paper.hashCode());
    result = 31 * result + (this.digitalOnly == null ? 0: this.digitalOnly.hashCode());
    result = 31 * result + (this.products == null ? 0: this.products.hashCode());
    result = 31 * result + (this.offers == null ? 0: this.offers.hashCode());
    result = 31 * result + (this.campaigns == null ? 0: this.campaigns.hashCode());
    result = 31 * result + (this.nextDelivery == null ? 0: this.nextDelivery.hashCode());
    result = 31 * result + (this.canPause == null ? 0: this.canPause.hashCode());
    result = 31 * result + (this.canTempAddr == null ? 0: this.canTempAddr.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class ModelPackage {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  info: ").append(info).append("\n");
    sb.append("  paper: ").append(paper).append("\n");
    sb.append("  digitalOnly: ").append(digitalOnly).append("\n");
    sb.append("  products: ").append(products).append("\n");
    sb.append("  offers: ").append(offers).append("\n");
    sb.append("  campaigns: ").append(campaigns).append("\n");
    sb.append("  nextDelivery: ").append(nextDelivery).append("\n");
    sb.append("  canPause: ").append(canPause).append("\n");
    sb.append("  canTempAddr: ").append(canTempAddr).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
