/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Data for a delivery reclamation creation.
 **/
@ApiModel(description = "Data for a delivery reclamation creation.")
public class NewDeliveryReclamation {
  
  @SerializedName("paper")
  private String paper = null;
  @SerializedName("publicationDate")
  private Date publicationDate = null;
  public enum ClaimEnum {
     Extension,  NewDelivery, 
  };
  @SerializedName("claim")
  private ClaimEnum claim = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPaper() {
    return paper;
  }
  public void setPaper(String paper) {
    this.paper = paper;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getPublicationDate() {
    return publicationDate;
  }
  public void setPublicationDate(Date publicationDate) {
    this.publicationDate = publicationDate;
  }

  /**
   * The type of claim for the reclamation
   **/
  @ApiModelProperty(required = true, value = "The type of claim for the reclamation")
  public ClaimEnum getClaim() {
    return claim;
  }
  public void setClaim(ClaimEnum claim) {
    this.claim = claim;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewDeliveryReclamation newDeliveryReclamation = (NewDeliveryReclamation) o;
    return (this.paper == null ? newDeliveryReclamation.paper == null : this.paper.equals(newDeliveryReclamation.paper)) &&
        (this.publicationDate == null ? newDeliveryReclamation.publicationDate == null : this.publicationDate.equals(newDeliveryReclamation.publicationDate)) &&
        (this.claim == null ? newDeliveryReclamation.claim == null : this.claim.equals(newDeliveryReclamation.claim));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.paper == null ? 0: this.paper.hashCode());
    result = 31 * result + (this.publicationDate == null ? 0: this.publicationDate.hashCode());
    result = 31 * result + (this.claim == null ? 0: this.claim.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewDeliveryReclamation {\n");
    
    sb.append("  paper: ").append(paper).append("\n");
    sb.append("  publicationDate: ").append(publicationDate).append("\n");
    sb.append("  claim: ").append(claim).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
