/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.LegalConsent;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class NewTemporaryUser {
  
  @SerializedName("emailAddress")
  private String emailAddress = null;
  @SerializedName("legalConsents")
  private List<LegalConsent> legalConsents = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getEmailAddress() {
    return emailAddress;
  }
  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<LegalConsent> getLegalConsents() {
    return legalConsents;
  }
  public void setLegalConsents(List<LegalConsent> legalConsents) {
    this.legalConsents = legalConsents;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewTemporaryUser newTemporaryUser = (NewTemporaryUser) o;
    return (this.emailAddress == null ? newTemporaryUser.emailAddress == null : this.emailAddress.equals(newTemporaryUser.emailAddress)) &&
        (this.legalConsents == null ? newTemporaryUser.legalConsents == null : this.legalConsents.equals(newTemporaryUser.legalConsents));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.emailAddress == null ? 0: this.emailAddress.hashCode());
    result = 31 * result + (this.legalConsents == null ? 0: this.legalConsents.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewTemporaryUser {\n");
    
    sb.append("  emailAddress: ").append(emailAddress).append("\n");
    sb.append("  legalConsents: ").append(legalConsents).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
