/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class NewUser {
  
  @SerializedName("newUserFirstName")
  private String newUserFirstName = null;
  @SerializedName("newUserLastName")
  private String newUserLastName = null;
  @SerializedName("newUserEmailAddress")
  private String newUserEmailAddress = null;
  @SerializedName("newUserPassword")
  private String newUserPassword = null;
  @SerializedName("newUserConfirmPassword")
  private String newUserConfirmPassword = null;
  @SerializedName("newUserStreetAddress")
  private String newUserStreetAddress = null;
  @SerializedName("newUserZipCode")
  private String newUserZipCode = null;
  @SerializedName("newUserCity")
  private String newUserCity = null;
  @SerializedName("newUserCountry")
  private String newUserCountry = null;
  @SerializedName("newUserPhone")
  private String newUserPhone = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNewUserFirstName() {
    return newUserFirstName;
  }
  public void setNewUserFirstName(String newUserFirstName) {
    this.newUserFirstName = newUserFirstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNewUserLastName() {
    return newUserLastName;
  }
  public void setNewUserLastName(String newUserLastName) {
    this.newUserLastName = newUserLastName;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getNewUserEmailAddress() {
    return newUserEmailAddress;
  }
  public void setNewUserEmailAddress(String newUserEmailAddress) {
    this.newUserEmailAddress = newUserEmailAddress;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getNewUserPassword() {
    return newUserPassword;
  }
  public void setNewUserPassword(String newUserPassword) {
    this.newUserPassword = newUserPassword;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getNewUserConfirmPassword() {
    return newUserConfirmPassword;
  }
  public void setNewUserConfirmPassword(String newUserConfirmPassword) {
    this.newUserConfirmPassword = newUserConfirmPassword;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNewUserStreetAddress() {
    return newUserStreetAddress;
  }
  public void setNewUserStreetAddress(String newUserStreetAddress) {
    this.newUserStreetAddress = newUserStreetAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNewUserZipCode() {
    return newUserZipCode;
  }
  public void setNewUserZipCode(String newUserZipCode) {
    this.newUserZipCode = newUserZipCode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNewUserCity() {
    return newUserCity;
  }
  public void setNewUserCity(String newUserCity) {
    this.newUserCity = newUserCity;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNewUserCountry() {
    return newUserCountry;
  }
  public void setNewUserCountry(String newUserCountry) {
    this.newUserCountry = newUserCountry;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getNewUserPhone() {
    return newUserPhone;
  }
  public void setNewUserPhone(String newUserPhone) {
    this.newUserPhone = newUserPhone;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NewUser newUser = (NewUser) o;
    return (this.newUserFirstName == null ? newUser.newUserFirstName == null : this.newUserFirstName.equals(newUser.newUserFirstName)) &&
        (this.newUserLastName == null ? newUser.newUserLastName == null : this.newUserLastName.equals(newUser.newUserLastName)) &&
        (this.newUserEmailAddress == null ? newUser.newUserEmailAddress == null : this.newUserEmailAddress.equals(newUser.newUserEmailAddress)) &&
        (this.newUserPassword == null ? newUser.newUserPassword == null : this.newUserPassword.equals(newUser.newUserPassword)) &&
        (this.newUserConfirmPassword == null ? newUser.newUserConfirmPassword == null : this.newUserConfirmPassword.equals(newUser.newUserConfirmPassword)) &&
        (this.newUserStreetAddress == null ? newUser.newUserStreetAddress == null : this.newUserStreetAddress.equals(newUser.newUserStreetAddress)) &&
        (this.newUserZipCode == null ? newUser.newUserZipCode == null : this.newUserZipCode.equals(newUser.newUserZipCode)) &&
        (this.newUserCity == null ? newUser.newUserCity == null : this.newUserCity.equals(newUser.newUserCity)) &&
        (this.newUserCountry == null ? newUser.newUserCountry == null : this.newUserCountry.equals(newUser.newUserCountry)) &&
        (this.newUserPhone == null ? newUser.newUserPhone == null : this.newUserPhone.equals(newUser.newUserPhone));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.newUserFirstName == null ? 0: this.newUserFirstName.hashCode());
    result = 31 * result + (this.newUserLastName == null ? 0: this.newUserLastName.hashCode());
    result = 31 * result + (this.newUserEmailAddress == null ? 0: this.newUserEmailAddress.hashCode());
    result = 31 * result + (this.newUserPassword == null ? 0: this.newUserPassword.hashCode());
    result = 31 * result + (this.newUserConfirmPassword == null ? 0: this.newUserConfirmPassword.hashCode());
    result = 31 * result + (this.newUserStreetAddress == null ? 0: this.newUserStreetAddress.hashCode());
    result = 31 * result + (this.newUserZipCode == null ? 0: this.newUserZipCode.hashCode());
    result = 31 * result + (this.newUserCity == null ? 0: this.newUserCity.hashCode());
    result = 31 * result + (this.newUserCountry == null ? 0: this.newUserCountry.hashCode());
    result = 31 * result + (this.newUserPhone == null ? 0: this.newUserPhone.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class NewUser {\n");
    
    sb.append("  newUserFirstName: ").append(newUserFirstName).append("\n");
    sb.append("  newUserLastName: ").append(newUserLastName).append("\n");
    sb.append("  newUserEmailAddress: ").append(newUserEmailAddress).append("\n");
    sb.append("  newUserPassword: ").append(newUserPassword).append("\n");
    sb.append("  newUserConfirmPassword: ").append(newUserConfirmPassword).append("\n");
    sb.append("  newUserStreetAddress: ").append(newUserStreetAddress).append("\n");
    sb.append("  newUserZipCode: ").append(newUserZipCode).append("\n");
    sb.append("  newUserCity: ").append(newUserCity).append("\n");
    sb.append("  newUserCountry: ").append(newUserCountry).append("\n");
    sb.append("  newUserPhone: ").append(newUserPhone).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
