/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PackageOffer {
  
  @SerializedName("months")
  private Integer months = null;
  @SerializedName("totalPrice")
  private Integer totalPrice = null;
  @SerializedName("monthlyPrice")
  private Integer monthlyPrice = null;

  /**
   * Duration of the offer
   * minimum: -9223372036854775808
   * maximum: 9223372036854775807
   **/
  @ApiModelProperty(required = true, value = "Duration of the offer")
  public Integer getMonths() {
    return months;
  }
  public void setMonths(Integer months) {
    this.months = months;
  }

  /**
   * Amount of cents that has to be paid
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "Amount of cents that has to be paid")
  public Integer getTotalPrice() {
    return totalPrice;
  }
  public void setTotalPrice(Integer totalPrice) {
    this.totalPrice = totalPrice;
  }

  /**
   * Amount of cents that has to be paid
   * minimum: 0
   **/
  @ApiModelProperty(required = true, value = "Amount of cents that has to be paid")
  public Integer getMonthlyPrice() {
    return monthlyPrice;
  }
  public void setMonthlyPrice(Integer monthlyPrice) {
    this.monthlyPrice = monthlyPrice;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageOffer packageOffer = (PackageOffer) o;
    return (this.months == null ? packageOffer.months == null : this.months.equals(packageOffer.months)) &&
        (this.totalPrice == null ? packageOffer.totalPrice == null : this.totalPrice.equals(packageOffer.totalPrice)) &&
        (this.monthlyPrice == null ? packageOffer.monthlyPrice == null : this.monthlyPrice.equals(packageOffer.monthlyPrice));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.months == null ? 0: this.months.hashCode());
    result = 31 * result + (this.totalPrice == null ? 0: this.totalPrice.hashCode());
    result = 31 * result + (this.monthlyPrice == null ? 0: this.monthlyPrice.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageOffer {\n");
    
    sb.append("  months: ").append(months).append("\n");
    sb.append("  totalPrice: ").append(totalPrice).append("\n");
    sb.append("  monthlyPrice: ").append(monthlyPrice).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
