/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PackageCampaign {
  
  @SerializedName("no")
  private Integer no = null;
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("priceEur")
  private Double priceEur = null;
  @SerializedName("length")
  private Integer length = null;
  public enum LengthUnitEnum {
     Day,  Week,  Month,  Year, 
  };
  @SerializedName("lengthUnit")
  private LengthUnitEnum lengthUnit = null;
  @SerializedName("startDay")
  private Date startDay = null;
  @SerializedName("endDay")
  private Date endDay = null;

  /**
   * Campaign number
   * minimum: -9223372036854775808
   * maximum: 9223372036854775807
   **/
  @ApiModelProperty(required = true, value = "Campaign number")
  public Integer getNo() {
    return no;
  }
  public void setNo(Integer no) {
    this.no = no;
  }

  /**
   * Campaign id
   **/
  @ApiModelProperty(required = true, value = "Campaign id")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   * Campaign name
   **/
  @ApiModelProperty(required = true, value = "Campaign name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Price of campaign in euros
   **/
  @ApiModelProperty(required = true, value = "Price of campaign in euros")
  public Double getPriceEur() {
    return priceEur;
  }
  public void setPriceEur(Double priceEur) {
    this.priceEur = priceEur;
  }

  /**
   * Length of campaign
   * minimum: -9223372036854775808
   * maximum: 9223372036854775807
   **/
  @ApiModelProperty(required = true, value = "Length of campaign")
  public Integer getLength() {
    return length;
  }
  public void setLength(Integer length) {
    this.length = length;
  }

  /**
   * Unit of length (days, weeks, months, years)
   **/
  @ApiModelProperty(required = true, value = "Unit of length (days, weeks, months, years)")
  public LengthUnitEnum getLengthUnit() {
    return lengthUnit;
  }
  public void setLengthUnit(LengthUnitEnum lengthUnit) {
    this.lengthUnit = lengthUnit;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getStartDay() {
    return startDay;
  }
  public void setStartDay(Date startDay) {
    this.startDay = startDay;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getEndDay() {
    return endDay;
  }
  public void setEndDay(Date endDay) {
    this.endDay = endDay;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageCampaign packageCampaign = (PackageCampaign) o;
    return (this.no == null ? packageCampaign.no == null : this.no.equals(packageCampaign.no)) &&
        (this.id == null ? packageCampaign.id == null : this.id.equals(packageCampaign.id)) &&
        (this.name == null ? packageCampaign.name == null : this.name.equals(packageCampaign.name)) &&
        (this.priceEur == null ? packageCampaign.priceEur == null : this.priceEur.equals(packageCampaign.priceEur)) &&
        (this.length == null ? packageCampaign.length == null : this.length.equals(packageCampaign.length)) &&
        (this.lengthUnit == null ? packageCampaign.lengthUnit == null : this.lengthUnit.equals(packageCampaign.lengthUnit)) &&
        (this.startDay == null ? packageCampaign.startDay == null : this.startDay.equals(packageCampaign.startDay)) &&
        (this.endDay == null ? packageCampaign.endDay == null : this.endDay.equals(packageCampaign.endDay));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.no == null ? 0: this.no.hashCode());
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.priceEur == null ? 0: this.priceEur.hashCode());
    result = 31 * result + (this.length == null ? 0: this.length.hashCode());
    result = 31 * result + (this.lengthUnit == null ? 0: this.lengthUnit.hashCode());
    result = 31 * result + (this.startDay == null ? 0: this.startDay.hashCode());
    result = 31 * result + (this.endDay == null ? 0: this.endDay.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageCampaign {\n");
    
    sb.append("  no: ").append(no).append("\n");
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  priceEur: ").append(priceEur).append("\n");
    sb.append("  length: ").append(length).append("\n");
    sb.append("  lengthUnit: ").append(lengthUnit).append("\n");
    sb.append("  startDay: ").append(startDay).append("\n");
    sb.append("  endDay: ").append(endDay).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
