/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.DescriptionFrequency;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PackageDescription {
  
  @SerializedName("brand")
  private String brand = null;
  @SerializedName("brandLong")
  private String brandLong = null;
  @SerializedName("descShort")
  private String descShort = null;
  @SerializedName("descLong")
  private String descLong = null;
  @SerializedName("url")
  private String url = null;
  @SerializedName("days")
  private String days = null;
  @SerializedName("weekdays")
  private String weekdays = null;
  @SerializedName("frequency")
  private DescriptionFrequency frequency = null;
  @SerializedName("includes")
  private List<String> includes = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getBrand() {
    return brand;
  }
  public void setBrand(String brand) {
    this.brand = brand;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getBrandLong() {
    return brandLong;
  }
  public void setBrandLong(String brandLong) {
    this.brandLong = brandLong;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDescShort() {
    return descShort;
  }
  public void setDescShort(String descShort) {
    this.descShort = descShort;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDescLong() {
    return descLong;
  }
  public void setDescLong(String descLong) {
    this.descLong = descLong;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getUrl() {
    return url;
  }
  public void setUrl(String url) {
    this.url = url;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getDays() {
    return days;
  }
  public void setDays(String days) {
    this.days = days;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getWeekdays() {
    return weekdays;
  }
  public void setWeekdays(String weekdays) {
    this.weekdays = weekdays;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public DescriptionFrequency getFrequency() {
    return frequency;
  }
  public void setFrequency(DescriptionFrequency frequency) {
    this.frequency = frequency;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getIncludes() {
    return includes;
  }
  public void setIncludes(List<String> includes) {
    this.includes = includes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PackageDescription packageDescription = (PackageDescription) o;
    return (this.brand == null ? packageDescription.brand == null : this.brand.equals(packageDescription.brand)) &&
        (this.brandLong == null ? packageDescription.brandLong == null : this.brandLong.equals(packageDescription.brandLong)) &&
        (this.descShort == null ? packageDescription.descShort == null : this.descShort.equals(packageDescription.descShort)) &&
        (this.descLong == null ? packageDescription.descLong == null : this.descLong.equals(packageDescription.descLong)) &&
        (this.url == null ? packageDescription.url == null : this.url.equals(packageDescription.url)) &&
        (this.days == null ? packageDescription.days == null : this.days.equals(packageDescription.days)) &&
        (this.weekdays == null ? packageDescription.weekdays == null : this.weekdays.equals(packageDescription.weekdays)) &&
        (this.frequency == null ? packageDescription.frequency == null : this.frequency.equals(packageDescription.frequency)) &&
        (this.includes == null ? packageDescription.includes == null : this.includes.equals(packageDescription.includes));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.brand == null ? 0: this.brand.hashCode());
    result = 31 * result + (this.brandLong == null ? 0: this.brandLong.hashCode());
    result = 31 * result + (this.descShort == null ? 0: this.descShort.hashCode());
    result = 31 * result + (this.descLong == null ? 0: this.descLong.hashCode());
    result = 31 * result + (this.url == null ? 0: this.url.hashCode());
    result = 31 * result + (this.days == null ? 0: this.days.hashCode());
    result = 31 * result + (this.weekdays == null ? 0: this.weekdays.hashCode());
    result = 31 * result + (this.frequency == null ? 0: this.frequency.hashCode());
    result = 31 * result + (this.includes == null ? 0: this.includes.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PackageDescription {\n");
    
    sb.append("  brand: ").append(brand).append("\n");
    sb.append("  brandLong: ").append(brandLong).append("\n");
    sb.append("  descShort: ").append(descShort).append("\n");
    sb.append("  descLong: ").append(descLong).append("\n");
    sb.append("  url: ").append(url).append("\n");
    sb.append("  days: ").append(days).append("\n");
    sb.append("  weekdays: ").append(weekdays).append("\n");
    sb.append("  frequency: ").append(frequency).append("\n");
    sb.append("  includes: ").append(includes).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
