/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class PastTemporaryAddress {
  
  @SerializedName("countryCode")
  private String countryCode = null;
  @SerializedName("zipcode")
  private String zipcode = null;
  @SerializedName("cityName")
  private String cityName = null;
  @SerializedName("street")
  private String street = null;
  @SerializedName("temporaryName")
  private String temporaryName = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCountryCode() {
    return countryCode;
  }
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getZipcode() {
    return zipcode;
  }
  public void setZipcode(String zipcode) {
    this.zipcode = zipcode;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getCityName() {
    return cityName;
  }
  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getStreet() {
    return street;
  }
  public void setStreet(String street) {
    this.street = street;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getTemporaryName() {
    return temporaryName;
  }
  public void setTemporaryName(String temporaryName) {
    this.temporaryName = temporaryName;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PastTemporaryAddress pastTemporaryAddress = (PastTemporaryAddress) o;
    return (this.countryCode == null ? pastTemporaryAddress.countryCode == null : this.countryCode.equals(pastTemporaryAddress.countryCode)) &&
        (this.zipcode == null ? pastTemporaryAddress.zipcode == null : this.zipcode.equals(pastTemporaryAddress.zipcode)) &&
        (this.cityName == null ? pastTemporaryAddress.cityName == null : this.cityName.equals(pastTemporaryAddress.cityName)) &&
        (this.street == null ? pastTemporaryAddress.street == null : this.street.equals(pastTemporaryAddress.street)) &&
        (this.temporaryName == null ? pastTemporaryAddress.temporaryName == null : this.temporaryName.equals(pastTemporaryAddress.temporaryName));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.countryCode == null ? 0: this.countryCode.hashCode());
    result = 31 * result + (this.zipcode == null ? 0: this.zipcode.hashCode());
    result = 31 * result + (this.cityName == null ? 0: this.cityName.hashCode());
    result = 31 * result + (this.street == null ? 0: this.street.hashCode());
    result = 31 * result + (this.temporaryName == null ? 0: this.temporaryName.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class PastTemporaryAddress {\n");
    
    sb.append("  countryCode: ").append(countryCode).append("\n");
    sb.append("  zipcode: ").append(zipcode).append("\n");
    sb.append("  cityName: ").append(cityName).append("\n");
    sb.append("  street: ").append(street).append("\n");
    sb.append("  temporaryName: ").append(temporaryName).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
