/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import org.openapitools.client.model.ActiveDays;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Product {
  
  @SerializedName("id")
  private String id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("active")
  private ActiveDays active = null;
  @SerializedName("nextDelivery")
  private Date nextDelivery = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public ActiveDays getActive() {
    return active;
  }
  public void setActive(ActiveDays active) {
    this.active = active;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getNextDelivery() {
    return nextDelivery;
  }
  public void setNextDelivery(Date nextDelivery) {
    this.nextDelivery = nextDelivery;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Product product = (Product) o;
    return (this.id == null ? product.id == null : this.id.equals(product.id)) &&
        (this.name == null ? product.name == null : this.name.equals(product.name)) &&
        (this.active == null ? product.active == null : this.active.equals(product.active)) &&
        (this.nextDelivery == null ? product.nextDelivery == null : this.nextDelivery.equals(product.nextDelivery));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.active == null ? 0: this.active.hashCode());
    result = 31 * result + (this.nextDelivery == null ? 0: this.nextDelivery.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Product {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  active: ").append(active).append("\n");
    sb.append("  nextDelivery: ").append(nextDelivery).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
