/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.Campaign;
import org.openapitools.client.model.ModelPackage;
import org.openapitools.client.model.PausedSubscription;
import org.openapitools.client.model.SubscriptionDates;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Subscription {
  
  @SerializedName("subsno")
  private Integer subsno = null;
  @SerializedName("extno")
  private Integer extno = null;
  @SerializedName("cusno")
  private Integer cusno = null;
  @SerializedName("paycusno")
  private Integer paycusno = null;
  @SerializedName("kind")
  private String kind = null;
  @SerializedName("state")
  private String state = null;
  @SerializedName("pricegroup")
  private String pricegroup = null;
  @SerializedName("package")
  private ModelPackage _package = null;
  @SerializedName("dates")
  private SubscriptionDates dates = null;
  @SerializedName("extsubsexists")
  private Boolean extsubsexists = null;
  @SerializedName("campaign")
  private Campaign campaign = null;
  @SerializedName("paused")
  private List<PausedSubscription> paused = null;

  /**
   * minimum: -9223372036854775808
   * maximum: 9223372036854775807
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getSubsno() {
    return subsno;
  }
  public void setSubsno(Integer subsno) {
    this.subsno = subsno;
  }

  /**
   * minimum: -9223372036854775808
   * maximum: 9223372036854775807
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getExtno() {
    return extno;
  }
  public void setExtno(Integer extno) {
    this.extno = extno;
  }

  /**
   * minimum: -9223372036854775808
   * maximum: 9223372036854775807
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getCusno() {
    return cusno;
  }
  public void setCusno(Integer cusno) {
    this.cusno = cusno;
  }

  /**
   * minimum: -9223372036854775808
   * maximum: 9223372036854775807
   **/
  @ApiModelProperty(required = true, value = "")
  public Integer getPaycusno() {
    return paycusno;
  }
  public void setPaycusno(Integer paycusno) {
    this.paycusno = paycusno;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getKind() {
    return kind;
  }
  public void setKind(String kind) {
    this.kind = kind;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getState() {
    return state;
  }
  public void setState(String state) {
    this.state = state;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getPricegroup() {
    return pricegroup;
  }
  public void setPricegroup(String pricegroup) {
    this.pricegroup = pricegroup;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public ModelPackage getPackage() {
    return _package;
  }
  public void setPackage(ModelPackage _package) {
    this._package = _package;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public SubscriptionDates getDates() {
    return dates;
  }
  public void setDates(SubscriptionDates dates) {
    this.dates = dates;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Boolean getExtsubsexists() {
    return extsubsexists;
  }
  public void setExtsubsexists(Boolean extsubsexists) {
    this.extsubsexists = extsubsexists;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Campaign getCampaign() {
    return campaign;
  }
  public void setCampaign(Campaign campaign) {
    this.campaign = campaign;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<PausedSubscription> getPaused() {
    return paused;
  }
  public void setPaused(List<PausedSubscription> paused) {
    this.paused = paused;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Subscription subscription = (Subscription) o;
    return (this.subsno == null ? subscription.subsno == null : this.subsno.equals(subscription.subsno)) &&
        (this.extno == null ? subscription.extno == null : this.extno.equals(subscription.extno)) &&
        (this.cusno == null ? subscription.cusno == null : this.cusno.equals(subscription.cusno)) &&
        (this.paycusno == null ? subscription.paycusno == null : this.paycusno.equals(subscription.paycusno)) &&
        (this.kind == null ? subscription.kind == null : this.kind.equals(subscription.kind)) &&
        (this.state == null ? subscription.state == null : this.state.equals(subscription.state)) &&
        (this.pricegroup == null ? subscription.pricegroup == null : this.pricegroup.equals(subscription.pricegroup)) &&
        (this._package == null ? subscription._package == null : this._package.equals(subscription._package)) &&
        (this.dates == null ? subscription.dates == null : this.dates.equals(subscription.dates)) &&
        (this.extsubsexists == null ? subscription.extsubsexists == null : this.extsubsexists.equals(subscription.extsubsexists)) &&
        (this.campaign == null ? subscription.campaign == null : this.campaign.equals(subscription.campaign)) &&
        (this.paused == null ? subscription.paused == null : this.paused.equals(subscription.paused));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.subsno == null ? 0: this.subsno.hashCode());
    result = 31 * result + (this.extno == null ? 0: this.extno.hashCode());
    result = 31 * result + (this.cusno == null ? 0: this.cusno.hashCode());
    result = 31 * result + (this.paycusno == null ? 0: this.paycusno.hashCode());
    result = 31 * result + (this.kind == null ? 0: this.kind.hashCode());
    result = 31 * result + (this.state == null ? 0: this.state.hashCode());
    result = 31 * result + (this.pricegroup == null ? 0: this.pricegroup.hashCode());
    result = 31 * result + (this._package == null ? 0: this._package.hashCode());
    result = 31 * result + (this.dates == null ? 0: this.dates.hashCode());
    result = 31 * result + (this.extsubsexists == null ? 0: this.extsubsexists.hashCode());
    result = 31 * result + (this.campaign == null ? 0: this.campaign.hashCode());
    result = 31 * result + (this.paused == null ? 0: this.paused.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Subscription {\n");
    
    sb.append("  subsno: ").append(subsno).append("\n");
    sb.append("  extno: ").append(extno).append("\n");
    sb.append("  cusno: ").append(cusno).append("\n");
    sb.append("  paycusno: ").append(paycusno).append("\n");
    sb.append("  kind: ").append(kind).append("\n");
    sb.append("  state: ").append(state).append("\n");
    sb.append("  pricegroup: ").append(pricegroup).append("\n");
    sb.append("  _package: ").append(_package).append("\n");
    sb.append("  dates: ").append(dates).append("\n");
    sb.append("  extsubsexists: ").append(extsubsexists).append("\n");
    sb.append("  campaign: ").append(campaign).append("\n");
    sb.append("  paused: ").append(paused).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
