/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TemporaryAddressChangeDates {
  
  @SerializedName("oldStartDate")
  private Date oldStartDate = null;
  @SerializedName("newStartDate")
  private Date newStartDate = null;
  @SerializedName("newEndDate")
  private Date newEndDate = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getOldStartDate() {
    return oldStartDate;
  }
  public void setOldStartDate(Date oldStartDate) {
    this.oldStartDate = oldStartDate;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public Date getNewStartDate() {
    return newStartDate;
  }
  public void setNewStartDate(Date newStartDate) {
    this.newStartDate = newStartDate;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getNewEndDate() {
    return newEndDate;
  }
  public void setNewEndDate(Date newEndDate) {
    this.newEndDate = newEndDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TemporaryAddressChangeDates temporaryAddressChangeDates = (TemporaryAddressChangeDates) o;
    return (this.oldStartDate == null ? temporaryAddressChangeDates.oldStartDate == null : this.oldStartDate.equals(temporaryAddressChangeDates.oldStartDate)) &&
        (this.newStartDate == null ? temporaryAddressChangeDates.newStartDate == null : this.newStartDate.equals(temporaryAddressChangeDates.newStartDate)) &&
        (this.newEndDate == null ? temporaryAddressChangeDates.newEndDate == null : this.newEndDate.equals(temporaryAddressChangeDates.newEndDate));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.oldStartDate == null ? 0: this.oldStartDate.hashCode());
    result = 31 * result + (this.newStartDate == null ? 0: this.newStartDate.hashCode());
    result = 31 * result + (this.newEndDate == null ? 0: this.newEndDate.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TemporaryAddressChangeDates {\n");
    
    sb.append("  oldStartDate: ").append(oldStartDate).append("\n");
    sb.append("  newStartDate: ").append(newStartDate).append("\n");
    sb.append("  newEndDate: ").append(newEndDate).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
