/**
 * Persona
 * KSF Media unified login service
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import java.util.UUID;
import org.openapitools.client.model.Address;
import org.openapitools.client.model.Subscription;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class User {
  
  @SerializedName("uuid")
  private UUID uuid = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("firstName")
  private String firstName = null;
  @SerializedName("lastName")
  private String lastName = null;
  @SerializedName("address")
  private Address address = null;
  @SerializedName("cusno")
  private String cusno = null;
  @SerializedName("subs")
  private List<Subscription> subs = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public UUID getUuid() {
    return uuid;
  }
  public void setUuid(UUID uuid) {
    this.uuid = uuid;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Address getAddress() {
    return address;
  }
  public void setAddress(Address address) {
    this.address = address;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCusno() {
    return cusno;
  }
  public void setCusno(String cusno) {
    this.cusno = cusno;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public List<Subscription> getSubs() {
    return subs;
  }
  public void setSubs(List<Subscription> subs) {
    this.subs = subs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    User user = (User) o;
    return (this.uuid == null ? user.uuid == null : this.uuid.equals(user.uuid)) &&
        (this.email == null ? user.email == null : this.email.equals(user.email)) &&
        (this.firstName == null ? user.firstName == null : this.firstName.equals(user.firstName)) &&
        (this.lastName == null ? user.lastName == null : this.lastName.equals(user.lastName)) &&
        (this.address == null ? user.address == null : this.address.equals(user.address)) &&
        (this.cusno == null ? user.cusno == null : this.cusno.equals(user.cusno)) &&
        (this.subs == null ? user.subs == null : this.subs.equals(user.subs));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.uuid == null ? 0: this.uuid.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    result = 31 * result + (this.cusno == null ? 0: this.cusno.hashCode());
    result = 31 * result + (this.subs == null ? 0: this.subs.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class User {\n");
    
    sb.append("  uuid: ").append(uuid).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("  cusno: ").append(cusno).append("\n");
    sb.append("  subs: ").append(subs).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
