/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.Date;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserUpdateAddress {
  
  @SerializedName("countryCode")
  private String countryCode = null;
  @SerializedName("zipCode")
  private String zipCode = null;
  @SerializedName("streetAddress")
  private String streetAddress = null;
  @SerializedName("validFrom")
  private Date validFrom = null;

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getCountryCode() {
    return countryCode;
  }
  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getZipCode() {
    return zipCode;
  }
  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  /**
   **/
  @ApiModelProperty(required = true, value = "")
  public String getStreetAddress() {
    return streetAddress;
  }
  public void setStreetAddress(String streetAddress) {
    this.streetAddress = streetAddress;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Date getValidFrom() {
    return validFrom;
  }
  public void setValidFrom(Date validFrom) {
    this.validFrom = validFrom;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserUpdateAddress userUpdateAddress = (UserUpdateAddress) o;
    return (this.countryCode == null ? userUpdateAddress.countryCode == null : this.countryCode.equals(userUpdateAddress.countryCode)) &&
        (this.zipCode == null ? userUpdateAddress.zipCode == null : this.zipCode.equals(userUpdateAddress.zipCode)) &&
        (this.streetAddress == null ? userUpdateAddress.streetAddress == null : this.streetAddress.equals(userUpdateAddress.streetAddress)) &&
        (this.validFrom == null ? userUpdateAddress.validFrom == null : this.validFrom.equals(userUpdateAddress.validFrom));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.countryCode == null ? 0: this.countryCode.hashCode());
    result = 31 * result + (this.zipCode == null ? 0: this.zipCode.hashCode());
    result = 31 * result + (this.streetAddress == null ? 0: this.streetAddress.hashCode());
    result = 31 * result + (this.validFrom == null ? 0: this.validFrom.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserUpdateAddress {\n");
    
    sb.append("  countryCode: ").append(countryCode).append("\n");
    sb.append("  zipCode: ").append(zipCode).append("\n");
    sb.append("  streetAddress: ").append(streetAddress).append("\n");
    sb.append("  validFrom: ").append(validFrom).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
