/**
 * Persona
 * KSF Media unified login service
 *
 * The version of the OpenAPI document: 1.3.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model;

import java.util.*;
import org.openapitools.client.model.UserUpdateAddress;
import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class UserUpdate {
  
  @SerializedName("firstName")
  private String firstName = null;
  @SerializedName("lastName")
  private String lastName = null;
  @SerializedName("address")
  private UserUpdateAddress address = null;
  @SerializedName("email")
  private String email = null;
  @SerializedName("pendingAddressChanges")
  private List<Object> pendingAddressChanges = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getLastName() {
    return lastName;
  }
  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public UserUpdateAddress getAddress() {
    return address;
  }
  public void setAddress(UserUpdateAddress address) {
    this.address = address;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getEmail() {
    return email;
  }
  public void setEmail(String email) {
    this.email = email;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public List<Object> getPendingAddressChanges() {
    return pendingAddressChanges;
  }
  public void setPendingAddressChanges(List<Object> pendingAddressChanges) {
    this.pendingAddressChanges = pendingAddressChanges;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UserUpdate userUpdate = (UserUpdate) o;
    return (this.firstName == null ? userUpdate.firstName == null : this.firstName.equals(userUpdate.firstName)) &&
        (this.lastName == null ? userUpdate.lastName == null : this.lastName.equals(userUpdate.lastName)) &&
        (this.address == null ? userUpdate.address == null : this.address.equals(userUpdate.address)) &&
        (this.email == null ? userUpdate.email == null : this.email.equals(userUpdate.email)) &&
        (this.pendingAddressChanges == null ? userUpdate.pendingAddressChanges == null : this.pendingAddressChanges.equals(userUpdate.pendingAddressChanges));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.firstName == null ? 0: this.firstName.hashCode());
    result = 31 * result + (this.lastName == null ? 0: this.lastName.hashCode());
    result = 31 * result + (this.address == null ? 0: this.address.hashCode());
    result = 31 * result + (this.email == null ? 0: this.email.hashCode());
    result = 31 * result + (this.pendingAddressChanges == null ? 0: this.pendingAddressChanges.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class UserUpdate {\n");
    
    sb.append("  firstName: ").append(firstName).append("\n");
    sb.append("  lastName: ").append(lastName).append("\n");
    sb.append("  address: ").append(address).append("\n");
    sb.append("  email: ").append(email).append("\n");
    sb.append("  pendingAddressChanges: ").append(pendingAddressChanges).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
